### ISSUE TITLE
[Question] Ris message returns a matrix on Path

### ISSUE THREAD

**Issue by renanbastos93** [jaredmauch/rislive#4]
Hi, how are you?

I have a question, I am testing the RIS and I did see that it returns matrix on the path but I don't understand. Can you explain to me?

e.g
`"path": [202194, 6939, 6939, 6762, 23487, 27738, 27738, 27738, 27738, 27738, 27738, 27738, 27738, [27738]]`
```json
{
    "timestamp": 1571924617.22,
    "peer": "91.206.52.60",
    "peer_asn": "202194",
    "id": "91.206.52.60-1571924617.22-26992308",
    "host": "rrc20",
    "type": "UPDATE",
    "path": [202194, 6939, 6939, 6762, 23487, 27738, 27738, 27738, 27738, 27738, 27738, 27738, 27738, [27738]],
    "community": [[20219, 51], [20219, 6939]],
    "origin": "igp",
    "aggregator": "23487:200.124.224.2",
    "announcements": [
        {
            "next_hop": "91.206.52.170",
            "prefixes": [
                "201.183.255.0/24"
            ]
        }
    ]
}
```

**Comment by jaredmauch** [comment]
This is an AS_SET.

**Comment by renanbastos93** [comment]
> This is an AS_SET.

Thanks a lot, but sorry.

Shouldn't be 2 values on as_set, to be one aggregation?
Do you indicate a link for me read?

**Comment by jaredmauch** [comment]
The streamer just displays what comes in via ris live.  You likely want to contact RIPE about why they chose to format it that way.

**Comment by renanbastos93** [comment]
Thank you so much.

I'll to try talk with RIPE.
